package scan_test

// ParseAsset takes untrusted input: the CLI and the HTTP API hand it a raw
// CODE-ISSUER string straight from a user. The fuzz target below drives it
// with generated bytes so that a panic, a rejection that still returns a
// half-built asset, or an accepted identifier that does not round-trip is
// found by the fuzzer rather than by a caller.

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/use-assay/assay/internal/mechanics"
	"github.com/use-assay/assay/internal/scan"
)

// mechanicsTestdataDir resolves internal/mechanics/testdata relative to this
// test file, so the seeds load whether `go test` runs from the repo root or
// from the package directory.
func mechanicsTestdataDir(tb testing.TB) string {
	tb.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		tb.Fatal("runtime.Caller failed")
	}
	// internal/scan/fuzz_test.go -> internal/mechanics/testdata
	return filepath.Join(filepath.Dir(thisFile), "..", "mechanics", "testdata")
}

// fixtureAssets renders the canonical CODE-ISSUER form of every captured
// subject asset under internal/mechanics/testdata. Those fixtures are the
// scanner's own trusted evidence, so they make a realistic seed corpus for the
// identifier parser. Failing when none are found keeps the corpus from
// silently going empty after a fixture move.
func fixtureAssets(tb testing.TB) []string {
	tb.Helper()
	matches, err := filepath.Glob(filepath.Join(mechanicsTestdataDir(tb), "*", "asset.json"))
	if err != nil {
		tb.Fatalf("glob fixture assets: %v", err)
	}
	if len(matches) == 0 {
		tb.Fatal("no fixture asset.json files found; the seed corpus would be empty")
	}
	var out []string
	for _, path := range matches {
		raw, err := os.ReadFile(path)
		if err != nil {
			tb.Fatalf("read %s: %v", path, err)
		}
		var a struct {
			Code   string `json:"asset_code"`
			Issuer string `json:"asset_issuer"`
		}
		if err := json.Unmarshal(raw, &a); err != nil {
			tb.Fatalf("decode %s: %v", path, err)
		}
		if a.Code == "" || a.Issuer == "" {
			continue
		}
		out = append(out, a.Code+"-"+a.Issuer)
	}
	return out
}

// FuzzParseAsset asserts the two states ParseAsset can be in. An accepted
// input is fully populated and round-trips through its canonical rendering; a
// rejected one returns ErrBadAsset and the zero asset, never a partially
// populated result.
func FuzzParseAsset(f *testing.F) {
	const issuer = "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN"

	// Seed corpus: every case from TestParseAsset, accepted and rejected, plus
	// the captured subject assets.
	for _, in := range []string{
		"USDC-" + issuer,
		"  USDC-" + issuer + "  ",
		"USDC-" + issuer + "-1",
		"",
		"USDC",
		"-" + issuer,
		"USDC-NOTAKEY",
		"USDC-" + strings.ToLower(issuer),
		"TOOLONGASSETCODE-" + issuer,
		"US DC-" + issuer,
	} {
		f.Add(in)
	}
	for _, in := range fixtureAssets(f) {
		f.Add(in)
	}

	f.Fuzz(func(t *testing.T, in string) {
		a, err := scan.ParseAsset(in)
		if err != nil {
			// A rejected input must report ErrBadAsset and must not leave a
			// half-built asset for a caller to use by mistake.
			if !errors.Is(err, scan.ErrBadAsset) {
				t.Fatalf("ParseAsset(%q) error = %v, want ErrBadAsset", in, err)
			}
			if a != (mechanics.Asset{}) {
				t.Fatalf("ParseAsset(%q) rejected the input but returned %+v", in, a)
			}
			return
		}

		// An accepted input is fully populated and survives the canonical
		// CODE-ISSUER rendering unchanged.
		if a.Code == "" || a.Issuer == "" {
			t.Fatalf("ParseAsset(%q) accepted with an empty field: %+v", in, a)
		}
		rt, err := scan.ParseAsset(a.String())
		if err != nil {
			t.Fatalf("ParseAsset(%q) accepted as %q, which it then rejects: %v", in, a.String(), err)
		}
		if rt != a {
			t.Fatalf("ParseAsset(%q) = %+v; round-trip through %q gave %+v", in, a, a.String(), rt)
		}
	})
}
